[lint]
select = ["ALL"]
ignore = [
  "COM812",  # Trailing comma missing
  "D203",    # One-blank-line-before-class (conflicts with D211)
  "D213",    # Multi-line-summary-second-line (conflicts with D212)
  "ERA001",  # Found commented-out code
  "FBT003",  # Boolean positional value in function call
  "PLR0913", # Too many arguments in function definition
  "PLR2004", # Magic value used in comparison
]

[lint.per-file-ignores]
"convoviz/*" = [
  "TRY003",  # Avoid specifying long messages outside the exception class
  "C901",    # function is too complex
  "PLR0912", # Too many branches
  "PLR0915", # Too many statements
  "D417",    # Missing argument description in the docstring
  "G004",    # Logging statement uses f-string
  "FBT001",  # Boolean-typed positional argument in function definition
  "B008",    # Do not perform function call in argument defaults
  "ANN401",  # Dynamically typed expressions (Any) are disallowed
  "FBT002",  # Boolean default positional argument in function definition
  "D107",    # Missing docstring in __init__
  "BLE001",  # Do not catch blind exception
  "S112",    # try-except-continue detected
  "PLR0911", # Too many return statements
  "S110",    # try-except-pass detected
  "PLW2901", # for loop variable overwritten by assignment target
  "PERF401", # Use a list comprehension to create a transformed list
]

"tests/*" = [
  "ANN001",  # Missing type annotation for function argument
  "ANN202",  # missing-return-type-private-function
  "PLC0415", # import-outside-top-level
  "E501",    # line-too-long
  "S101",    # Use of assert detected
  "D100",    # Missing docstring in public module
  "D101",    # Missing docstring in public class
  "D102",    # Missing docstring in public method
  "D103",    # Missing docstring in public function
  "D401",    # First line should be in imperative mood
  "ANN201",  # Missing return type annotation for public function
  "ANN002",  # Missing type annotation for *args
  "ANN003",  # Missing type annotation for **kwargs
  "DTZ005",  # datetime.now() called without a tz argument
  "DTZ001",  # datetime.datetime() called without a tzinfo argument
]
